hydra:
  run:
    dir: .

seed: 42
raw_data_path: "gs://mlops-bucket-1999/data/raw/mental_disorders_reddit.csv"
output_folder: "gs://mlops-bucket-1999/data/processed"
training_data_path: "${output_folder}/training_data.pt"
testing_data_path: "${output_folder}/testing_data.pt"
tokenizer_name: "distilbert-base-uncased"
max_length: 512

batch_size: 32
num_workers: 4
data_percentage: 0.002
