defaults:
  - data
  - model
seed: 42
batch_size: 32
num_workers: 4
data_percentage: 0.1
training_data_path: ${output_folder}/training_data.pt
testing_data_path: ${output_folder}/testing_data.pt
model_path: "gs://mlops-bucket-1999/models/model.pth"
