defaults:
  - model

learning_rate: 2e-4
epochs: 5
total_training_steps: 1000
model_path: "gs://mlops-bucket-1999/models/model.pth"
wandb_project_name: "dtu-02476-mlops-project"
wandb_entity: "moorekevin-"
